### ISSUE TITLE
Image recognition working incorrectly for multi photos?

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-app#304]
Have just been running a few photos through the [demo page](https://irecord.app.flumens.io/demo.html). If I use the option to "Select multiple photos from your gallery" and choose photos showing a range of different species, it seems to give the same identification to all the photos. I think it is identifying the last photo to be uploaded, and ignoring the others.

Is that how it is intended to behave? If so we need to make it clear to users that the should only upload photos of one organism at a time. But I was expecting it to be able to deal with photos of more than one species?

**Comment by kazlauskis** [comment]
Thanks. I have fixed this now.

**Comment by kitenetter** [comment]
@kazlauskis I'm working on the Help text and am still not sure how the "Select multiple photos" option is supposed to work. I just tried it again on the demo page. I uploaded three different butterfly species, but am still seeing the same identification suggestion for each photo.

What should happen? Can the app offer more than one species identification at a time? And if it does, how should the user make use of this? I can't see how the multiple photos can be split into more than one record - but I'm still not sure if that is what is supposed to happen.

**Comment by kazlauskis** [comment]
@kitenetter If you attach 3 photos to an occurrence, these will be sent for ID together, so the suggestions will be for the 3 photos as a whole, not separately. This is different from the previous app version where the Drupal module accepted a single image only, so the suggestions were per-photo. 

I don't know why different species photos still give us suggestions. I would have expected the classifier to return very low probabilities or no suggestions at all for such requests or similar. I have tried this now and the effect of attaching a different species photo to the top species score is very small. It changes the probability a bit but if the AI thinks one of the images has a clear match of a species, then that's what's going to be returned. That's my interpretation of this.

**Comment by kitenetter** [comment]
@kazlauskis thanks, I was misunderstanding what the app would do. I think what you are saying is this:
- If you use the "Select multiple photos" option it allows you to upload more than one photo, but we are intending people to use this for **_multiple photos of the same organism_**, and not for photos of a range of different organisms.
- The suggested ID will be a 'best estimate' based on the complete set of photos
- Once an ID has been selected by the user, the record will be saved as a single occurrence of a single species with multiple photos attached

I will update the Help text in a moment, and add it to #305 - closing this one.
